
# **Data Preprocessing & Feature Preparation**

# Text Cleaning

## **READ DATA**

In [ ]:
import os

print(os.path.exists("/fake_job_core_clean_FIXED.csv"))
print(os.path.getsize("/fake_job_core_clean_FIXED.csv") / (1024 * 1024), "MB")

True
90.19449710845947 MB

In [ ]:
import pandas as pd

df = pd.read_csv(
    "/fake_job_core_clean_FIXED.csv",
    engine="python"
)

print("Shape:", df.shape)
display(df.head())

Shape: (15870, 29)

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,...,content_hash,missing_company_profile,missing_requirements,missing_benefits,missing_salary_range,missing_employment_type,missing_required_experience,missing_required_education,missing_industry,missing_function
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,...,74e01d53f8b9614312ff9bd8ec915f8780e6e609367693...,0,0,1,1,0,0,1,1,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,...,b1efcbe814d56733dda29376f37ad4500a8573d78ee506...,0,0,0,1,0,0,1,0,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,...,10419657f58253a455abfb7bf67be0e6b971860b468af9...,0,0,1,1,1,1,1,1,1
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,...,4b6f0068b021b640c4f51bb6f5e4a530394625bcc6b21f...,0,0,0,1,0,0,0,0,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,...,7ee260dc67f202e80bb94f1d24ca7ab57c781e047eb97d...,0,0,0,1,0,0,0,0,0

##**Dataset overview**

In [ ]:
print("Rows", df.shape[0])
print("Columns", df.shape[1])
print("\nFeatures:")
display(df.columns)
print("\nUnique values:")
display(df.nunique)

Rows 15870
Columns 29

Features:

Index(['job_id', 'title', 'location', 'department', 'salary_range',
       'company_profile', 'description', 'requirements', 'benefits',
       'telecommuting', 'has_company_logo', 'has_questions', 'employment_type',
       'required_experience', 'required_education', 'industry', 'function',
       'fraudulent', 'structured_text', 'content_hash',
       'missing_company_profile', 'missing_requirements', 'missing_benefits',
       'missing_salary_range', 'missing_employment_type',
       'missing_required_experience', 'missing_required_education',
       'missing_industry', 'missing_function'],
      dtype='object')

Unique values:

<bound method DataFrame.nunique of        job_id                                              title  \
0           1                                   Marketing Intern
1           2          Customer Service - Cloud Video Production
2           3            Commissioning Machinery Assistant (CMA)
3           4                  Account Executive - Washington DC
4           5                                Bill Review Manager
...       ...                                                ...
15865   17875                               JavaScript Developer
15866   17876                    Account Director - Distribution
15867   17877                                 Payroll Accountant
15868   17878  Project Cost Control Staff Engineer - Cost Con...
15869   17879                                   Graphic Designer

                   location  department  salary_range  \
0          US, NY, New York   Marketing           NaN
1            NZ, , Auckland     Success           NaN
2             US, IA, Wever         NaN           NaN
3        US, DC, Washington       Sales           NaN
4        US, FL, Fort Worth         NaN           NaN
...                     ...         ...           ...
15865                 US, ,         NaN  80000-100000
15866       CA, ON, Toronto       Sales           NaN
15867  US, PA, Philadelphia  Accounting           NaN
15868       US, TX, Houston         NaN           NaN
15869         NG, LA, Lagos         NaN           NaN

                                         company_profile  \
0      We're Food52, and we've created a groundbreaki...
1      90 Seconds, the worlds Cloud Video Production ...
2      Valor Services provides Workforce Solutions th...
3      Our passion for improving quality of life thro...
4      SpotSource Solutions LLC is a Global Human Cap...
...                                                  ...
15865                                                NaN
15866  Vend is looking for some awesome new talent to...
15867  WebLinc is the e-commerce platform and service...
15868  We Provide Full Time Permanent Positions for m...
15869                                                NaN

                                             description  \
0      Food52, a fast-growing, James Beard Award-winn...
1      Organised - Focused - Vibrant - Awesome!Do you...
2      Our client, located in Houston, is actively se...
3      THE COMPANY: ESRI – Environmental Systems Rese...
4      JOB TITLE: Itemization Review ManagerLOCATION:...
...                                                  ...
15865  Sr, JavaScript Developer Experience : 4-10 yea...
15866  Just in case this is the first time you’ve vis...
15867  The Payroll Accountant will focus primarily on...
15868  Experienced Project Cost Control Staff Enginee...
15869  Nemsia Studios is looking for an experienced v...

                                            requirements  \
0      Experience with content management systems a m...
1      What we expect from you:Your key responsibilit...
2      Implement pre-commissioning and commissioning ...
3      EDUCATION: Bachelor’s or Master’s in GIS, busi...
4      QUALIFICATIONS:RN license in the State of Texa...
...                                                  ...
15865                                                NaN
15866  To ace this role you:Will eat comprehensive St...
15867  - B.A. or B.S. in Accounting- Desire to have f...
15868  At least 12 years professional experience.Abil...
15869  1. Must be fluent in the latest versions of Co...

                                                benefits  telecommuting  ...  \
0                                                    NaN              0  ...
1      What you will get from usThrough being part of...              0  ...
2                                                    NaN              0  ...
3      Our culture is anything but corporate—we have ...              0  ...
4                                  Full Benefits Offered              0  ...
...                                                  ...            ...  ...
15865                                                NaN              0  ...
15866  What can you expect from us?We have an open cu...              0  ...
15867  Health & WellnessMedical planPrescription drug...              0  ...
15868                                                NaN              0  ...
15869  Competitive salary (compensation will be based...              0  ...

                                            content_hash  \
0      74e01d53f8b9614312ff9bd8ec915f8780e6e609367693...
1      b1efcbe814d56733dda29376f37ad4500a8573d78ee506...
2      10419657f58253a455abfb7bf67be0e6b971860b468af9...
3      4b6f0068b021b640c4f51bb6f5e4a530394625bcc6b21f...
4      7ee260dc67f202e80bb94f1d24ca7ab57c781e047eb97d...
...                                                  ...
15865  9a5d6827250135ba801e66482d2d290f5eb1cf349ab74b...
15866  0a69583052d5f58e7ec1d414467394f64c4a0d3d57fdbe...
15867  c44e2ac4b55752291e6d72290d7f2ed284af543979e840...
15868  cd397e3211d27e47286cd8e57bc394b0552f0d896bbb43...
15869  90476466dd539a65beb48ff159dd7034764dfb69a8bb5a...

       missing_company_profile missing_requirements missing_benefits  \
0                            0                    0                1
1                            0                    0                0
2                            0                    0                1
3                            0                    0                0
4                            0                    0                0
...                        ...                  ...              ...
15865                        1                    1                1
15866                        0                    0                0
15867                        0                    0                0
15868                        0                    0                1
15869                        1                    0                0

      missing_salary_range missing_employment_type  \
0                        1                       0
1                        1                       0
2                        1                       1
3                        1                       0
4                        1                       0
...                    ...                     ...
15865                    0                       0
15866                    1                       0
15867                    1                       0
15868                    1                       0
15869                    1                       0

      missing_required_experience  missing_required_education  \
0                               0                           1
1                               0                           1
2                               1                           1
3                               0                           0
4                               0                           0
...                           ...                         ...
15865                           0                           0
15866                           0                           1
15867                           0                           0
15868                           1                           1
15869                           0                           0

      missing_industry missing_function
0                    1                0
1                    0                0
2                    1                1
3                    0                0
4                    0                0
...                ...              ...
15865                0                0
15866                0                0
15867                0                0
15868                1                1
15869                0                0

[15870 rows x 29 columns]>

# Structured Text Construction

In [ ]:
print(df["fraudulent"].value_counts())

print("\nPercentage:")
print(df["fraudulent"].value_counts(normalize=True) * 100)

fraudulent
0    15159
1      711
Name: count, dtype: int64

Percentage:
fraudulent
0    95.519849
1     4.480151
Name: proportion, dtype: float64

##Missing Value Analysis

In [ ]:
missing = df.isnull().sum().sort_values(ascending=False)

print(missing[missing > 0])

salary_range           13178
department              9776
required_education      7361
benefits                6586
required_experience     5868
function                5358
industry                4461
employment_type         3184
company_profile         3059
requirements            2249
location                 335
dtype: int64

In [ ]:
missing_by_class = df.groupby("fraudulent").apply(
    lambda x: x.isnull().mean() * 100
)

display(missing_by_class.T.sort_values(by=1, ascending=False))

/tmp/ipykernel_2978/1787582608.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  missing_by_class = df.groupby("fraudulent").apply(

fraudulent                           0          1
salary_range                 83.508147  72.995781
company_profile              17.092156  65.822785
department                   61.679530  59.915612
required_education           46.249753  49.226442
required_experience          36.493172  47.257384
benefits                     41.321987  45.288326
function                     33.735735  34.317862
industry                     28.042747  29.535865
employment_type              19.922158  23.066104
requirements                 14.018075  17.440225
location                      2.104360   2.250352
title                         0.000000   0.000000
job_id                        0.000000   0.000000
has_questions                 0.000000   0.000000
has_company_logo              0.000000   0.000000
telecommuting                 0.000000   0.000000
description                   0.000000   0.000000
fraudulent                    0.000000   0.000000
structured_text               0.000000   0.000000
content_hash                  0.000000   0.000000
missing_company_profile       0.000000   0.000000
missing_requirements          0.000000   0.000000
missing_benefits              0.000000   0.000000
missing_salary_range          0.000000   0.000000
missing_employment_type       0.000000   0.000000
missing_required_experience   0.000000   0.000000
missing_required_education    0.000000   0.000000
missing_industry              0.000000   0.000000
missing_function              0.000000   0.000000

In [ ]:
missing = df.isnull().sum().sort_values(ascending=False)

print("Missing values:")
print(missing[missing > 0])

Missing values:
salary_range           13178
department              9776
required_education      7361
benefits                6586
required_experience     5868
function                5358
industry                4461
employment_type         3184
company_profile         3059
requirements            2249
location                 335
dtype: int64

# Job Metadata Analysis

In [ ]:
print("Fraud Distribution:")
print(df["fraudulent"].value_counts())

print("\nPercentage:")
print((df["fraudulent"].value_counts(normalize=True) * 100).round(2))

Fraud Distribution:
fraudulent
0    15159
1      711
Name: count, dtype: int64

Percentage:
fraudulent
0    95.52
1     4.48
Name: proportion, dtype: float64

In [ ]:
metadata_cols = [
    "telecommuting",
    "has_company_logo",
    "has_questions",
    "employment_type"
]

for col in metadata_cols:
    print(f"\n{'='*50}")
    print(col)
    print(pd.crosstab(
        df[col],
        df["fraudulent"],
        normalize="columns"
    ).round(3))

==================================================
telecommuting
fraudulent         0      1
telecommuting
0              0.959  0.925
1              0.041  0.075

==================================================
has_company_logo
fraudulent            0     1
has_company_logo
0                 0.179  0.65
1                 0.821  0.35

==================================================
has_questions
fraudulent         0      1
has_questions
0              0.501  0.684
1              0.499  0.316

==================================================
employment_type
fraudulent           0      1
employment_type
Contract         0.065  0.062
Full-time        0.844  0.786
Other            0.017  0.020
Part-time        0.055  0.128
Temporary        0.019  0.004

## Fraud Rate Analysis

In [ ]:
for col in ["telecommuting", "has_company_logo", "has_questions", "employment_type"]:
    print(f"\n{'='*50}")
    print(f"Fraud rate by {col}")

    fraud_rate = df.groupby(col)["fraudulent"].mean() * 100
    print(fraud_rate.round(2).sort_values(ascending=False))

==================================================
Fraud rate by telecommuting
telecommuting
1    7.92
0    4.33
Name: fraudulent, dtype: float64

==================================================
Fraud rate by has_company_logo
has_company_logo
0    14.53
1     1.96
Name: fraudulent, dtype: float64

==================================================
Fraud rate by has_questions
has_questions
0    6.01
1    2.89
Name: fraudulent, dtype: float64

==================================================
Fraud rate by employment_type
employment_type
Part-time    9.47
Other        5.09
Contract     4.15
Full-time    4.03
Temporary    0.85
Name: fraudulent, dtype: float64

##Textual Feature Analysis

In [ ]:
text_cols = ["title", "company_profile", "description", "requirements", "benefits"]

for col in text_cols:
    df[f"{col}_length"] = df[col].fillna("").astype(str).str.len()

print("Average text length by class:\n")

display(
    df.groupby("fraudulent")[[
        f"{col}_length" for col in text_cols
    ]].mean().round(1)
)

Average text length by class:

,title_length,company_profile_length,description_length,requirements_length,benefits_length
fraudulent,,,,,
0,28.1,666.0,1240.0,630.4,218.6
1,27.9,246.8,1238.2,476.7,208.4

In [ ]:
print("===== FRAUDULENT JOB EXAMPLE =====")

fraud_job = df[df["fraudulent"] == 1].iloc[0]

print("\nTITLE:")
print(fraud_job["title"])

print("\nDESCRIPTION:")
print(fraud_job["description"][:1000])

print("\nREQUIREMENTS:")
print(fraud_job["requirements"][:700])

print("\n" + "="*70)

print("===== LEGITIMATE JOB EXAMPLE =====")

real_job = df[df["fraudulent"] == 0].iloc[0]

print("\nTITLE:")
print(real_job["title"])

print("\nDESCRIPTION:")
print(real_job["description"][:1000])

print("\nREQUIREMENTS:")
print(real_job["requirements"][:700])

===== FRAUDULENT JOB EXAMPLE =====

TITLE:
IC&E Technician

DESCRIPTION:
IC&E Technician | Bakersfield, CA Mt. PosoPrincipal Duties and Responsibilities: Calibrates, tests, maintains, troubleshoots, and installs all power plant instrumentation, control systems and electrical equipment.Performs maintenance on motor control centers, motor operated valves, generators, excitation equipment and motors.Performs preventive, predictive and corrective maintenance on equipment, coordinating work with various team members.Designs and installs new equipment and/or system modifications.Troubleshoots and performs maintenance on DC backup power equipment, process controls, programmable logic controls (PLC), and emission monitoring equipment.Uses maintenance reporting system to record time and material use, problem identified and corrected, and further action required; provides complete history of maintenance on equipment.Schedule, coordinate, work with and monitor contractors on specific tasks, as required.Follows safe working practices at all times.Identifies safety haza

REQUIREMENTS:
QualificationsKnowledge, Skills & Abilities: A high school diploma or GED is required. Must have a valid driver’s license. Ability to read, write, and communicate effectively in English. Good math skills. Four years of experience as an I&C Technician and/or Electrician in a power plant environment, preferably with a strong electrical background, up to and including, voltages to 15 KV to provide the following:Demonstrated knowledge of electrical equipment, electronics, schematics, basics of chemistry and physics and controls and instrumentation.Demonstrated knowledge of safe work practices associated with a power plant environment.Demonstrated ability to calibrate I&C systems and equipment, i

======================================================================
===== LEGITIMATE JOB EXAMPLE =====

TITLE:
Marketing Intern

DESCRIPTION:
Food52, a fast-growing, James Beard Award-winning online food community and crowd-sourced and curated recipe hub, is currently interviewing full- and part-time unpaid interns to work in a small team of editors, executives, and developers in its New York City headquarters.Reproducing and/or repackaging existing Food52 content for a number of partner sites, such as Huffington Post, Yahoo, Buzzfeed, and more in their various content management systemsResearching blogs and websites for the Provisions by Food52 Affiliate ProgramAssisting in day-to-day affiliate program support, such as screening affiliates and assisting in any affiliate inquiriesSupporting with PR & Events when neededHelping with office administrative work, such as filing, mailing, and preparing for meetingsWorking with developers to document bugs and suggest improvements to the siteSupporting the marketing and executive staff

REQUIREMENTS:
Experience with content management systems a major plus (any blogging counts!)Familiar with the Food52 editorial voice and aestheticLoves food, appreciates the importance of home cooking and cooking with the seasonsMeticulous editor, perfectionist, obsessive attention to detail, maddened by typos and broken links, delighted by finding and fixing themCheerful under pressureExcellent communication skillsA+ multi-tasker and juggler of responsibilities big and smallInterested in and engaged with social media like Twitter, Facebook, and PinterestLoves problem-solving and collaborating to drive Food52 forwardThinks big picture but pitches in on the nitty gritty of running a small company (dishes,

# MODEL TRAINING

## splitting data

In [ ]:
from sklearn.model_selection import train_test_split

# Features and target
X = df.drop(columns=["fraudulent"])
y = df["fraudulent"]

# First split: 70% train, 30% temporary
X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    stratify=y,
    random_state=42
)

# Second split: 15% validation, 15% test
X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    stratify=y_temp,
    random_state=42
)

print("Training:", X_train.shape)
print("Validation:", X_val.shape)
print("Testing:", X_test.shape)

print("\nFraud percentages:")
print("Train:", round(y_train.mean() * 100, 2), "%")
print("Validation:", round(y_val.mean() * 100, 2), "%")
print("Test:", round(y_test.mean() * 100, 2), "%")

Training: (11109, 33)
Validation: (2380, 33)
Testing: (2381, 33)

Fraud percentages:
Train: 4.48 %
Validation: 4.45 %
Test: 4.49 %

## Models

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# TF-IDF
tfidf = TfidfVectorizer(
    max_features=20000,
    ngram_range=(1, 2),
    min_df=2,
    sublinear_tf=True
)

X_train_tfidf = tfidf.fit_transform(X_train["structured_text"])
X_val_tfidf = tfidf.transform(X_val["structured_text"])

print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Validation TF-IDF shape:", X_val_tfidf.shape)

Training TF-IDF shape: (11109, 20000)
Validation TF-IDF shape: (2380, 20000)

In [ ]:
from sklearn.linear_model import LogisticRegression

baseline_model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

baseline_model.fit(X_train_tfidf, y_train)

print("Baseline model trained successfully.")

Baseline model trained successfully.

# BASELINE MODEL REPORT

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    average_precision_score,
    confusion_matrix
)

# Predictions
y_val_pred = baseline_model.predict(X_val_tfidf)
y_val_prob = baseline_model.predict_proba(X_val_tfidf)[:, 1]

# Metrics
print("Accuracy :", round(accuracy_score(y_val, y_val_pred), 4))
print("Precision:", round(precision_score(y_val, y_val_pred), 4))
print("Recall   :", round(recall_score(y_val, y_val_pred), 4))
print("F1 Score :", round(f1_score(y_val, y_val_pred), 4))
print("PR-AUC   :", round(average_precision_score(y_val, y_val_prob), 4))

print("\nConfusion Matrix:")
print(confusion_matrix(y_val, y_val_pred))

Accuracy : 0.9735
Precision: 0.6503
Recall   : 0.8774
F1 Score : 0.747
PR-AUC   : 0.8805

Confusion Matrix:
[[2224   50]
 [  13   93]]

In [ ]:
from sklearn.metrics import classification_report


print(classification_report(
    y_val,
    y_val_pred,
    target_names=["Legitimate", "Fraudulent"],
    digits=4
))

              precision    recall  f1-score   support

  Legitimate     0.9942    0.9780    0.9860      2274
  Fraudulent     0.6503    0.8774    0.7470       106

    accuracy                         0.9735      2380
   macro avg     0.8223    0.9277    0.8665      2380
weighted avg     0.9789    0.9735    0.9754      2380